#!/usr/bin/env php
<?php

if (!isset($argv[1])) {
    echo "You need to set domain name, for example: create-nginx-vhost mysite.ru\n";
    exit(1);
}

$domain = $argv[1];

if (file_exists('/var/www/' . $domain)) {
    echo "Domain $domain is exists.\n";
    exit(1);
}

$conf = '
server {
    server_name '.$domain.';
    root /var/www/'.$domain.'/web;
    error_log /var/log/nginx/'.$domain.'_errors.log;
    access_log /var/log/nginx/'.$domain.'_access.log;

    # Deny dot files
    location ~ /\.(ht|git) {
        deny all;
    }

    index index.php;

    location ~ \.php$ {
        try_files $uri = 404;
        fastcgi_pass unix:/var/run/php/php7.1-fpm.sock;
        include fastcgi_params;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
}
';

$robotsTxt = "
# www.robotstxt.org/
# www.google.com/support/webmasters/bin/answer.py?hl=en&answer=156449

User-Agent: *
Disallow: /cgi-bin/
Disallow: /admin/
";

file_put_contents('/etc/nginx/sites-enabled/'.$domain.'.conf', $conf);

mkdir("/var/www/{$domain}");
mkdir("/var/www/{$domain}/web");
file_put_contents("/var/www/{$domain}/web/index.php", $domain . ' is under construction...');
file_put_contents("/var/www/{$domain}/web/robots.txt", $robotsTxt);
system("chown -hR www-data:www-data /var/www/{$domain}/web");

system('/etc/init.d/nginx reload');
